-- MySQL Script generated by MySQL Workbench
-- Wed May  7 02:14:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`Guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`Guests` (
  `idG` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP,
  PRIMARY KEY (`idG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`Rooms` (
  `idR` INT NOT NULL AUTO_INCREMENT,
  `room_number` VARCHAR(10) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `status` ENUM('available', 'occupied', 'maintenance') NOT NULL,
  PRIMARY KEY (`idR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`Bookings` (
  `idB` INT NOT NULL AUTO_INCREMENT,
  `guest_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `check_in` DATE NOT NULL,
  `check_out` DATE NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idB`),
  INDEX `Rooms_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `Rooms`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel`.`Rooms` (`idR`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Guests`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel`.`Guests` (`idG`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
